### ISSUE TITLE
Изменение запросов при аутентификации

### ISSUE THREAD

**Issue by PetrGrachev** [zkryaev/timeline#12]
1.Изменить запрос POST /auth/register/user на 
{
"email": "string",
  "name": "string",
"password": "string"
}
Изменить запрос POST /auth/register/org на 
{
  "address": "string",
  "city": "string",
  "email": "string",
  "lat": 0,
  "long": 0,
  "name": "string",
  "password": "string",
  "type": "string"
}
2. После POST /auth/register/user помимо токенов нужно отправить id, иначе непонятно какой id отправлять при verify code
3. Почему токены отправляются и при Register User и при Verify Code?
4. Почему при Update Access Token обновляется только access token, почему не оба? Что будет если истечет и refresh token?
5. Добавь поле type в БД организаций

**Comment by zkryaev** [comment]
Поле type добавил.
Остальное обсудили. Фронт просто отправляет остальные поля пустыми.
