### ISSUE TITLE
Не работает на другом порте

### ISSUE THREAD

**Issue by PetrGrachev** [zkryaev/timeline#13]
При изменении порта в config/example.yml на другой, порт остается 8080
![image](https://github.com/user-attachments/assets/b82c4b18-b208-454e-8aab-29a843a2c11b)

**Comment by zkryaev** [comment]
Нашел проблему. Из-за http_server(а) не видел все вложенные параметры. Ввел HTTPServer в config.go, теперь норм парсится.
